# Generated by Django 3.2 on 2021-04-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('especificaciontecnica', models.TextField(max_length=300)),
                ('tiporeactor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'tiporeactor',
                'verbose_name_plural': 'tiporeactores',
                'ordering': ['tiporeactor'],
            },
        ),
    ]
