# Generated by Django 3.2 on 2021-04-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProsPyApp', '0003_cabatch_reactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen'),
        ),
    ]
