# Generated by Django 3.2 on 2021-04-23 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProsPyApp', '0004_auto_20210422_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=200)),
                ('x', models.FloatField(max_length=10)),
                ('v', models.FloatField(max_length=10)),
                ('so', models.FloatField(max_length=10)),
                ('umax', models.FloatField(max_length=10)),
                ('y', models.FloatField(max_length=10)),
                ('sf', models.FloatField(max_length=10)),
                ('tb', models.FloatField(max_length=10)),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProsPyApp.organismo')),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProsPyApp.reactor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'caprediccion',
                'verbose_name_plural': 'caprediccions',
                'ordering': ['titulo'],
            },
        ),
    ]
